steps:
  - label: "language check"
    command: echo "Watch your damn launguage!" | buildkite-agent annotate --style "warning"
    if: build.message =~ /.*fuck.*/
    plugins:
      - docker#v5.10.0:
          image: "artifactory.build.ue1.snooguts.net/reddit-docker-prod/android-dangerjs:2.0.0"

  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build
    plugins:
      - docker#v5.10.0:
          image: "artifactory.build.ue1.snooguts.net/reddit-docker-prod/android-dangerjs:2.0.0"

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build
    plugins:
      - docker#v5.10.0:
          image: "artifactory.build.ue1.snooguts.net/reddit-docker-prod/android-dangerjs:2.0.0"

  - label: "Dynamic Last Step"
    command: .buildkite/generate-moar-steps.sh | buildkite-agent pipeline upload
    key: deploy
    plugins:
      - docker#v5.10.0:
          image: "artifactory.build.ue1.snooguts.net/reddit-docker-prod/android-dangerjs:2.0.0"
